apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
#    appgw.ingress.kubernetes.io/backend-path-prefix: /
#    appgw.ingress.kubernetes.io/backend-protocol: https
#    kubernetes.io/ingress.class: addon-http-application-routing # using Azure nginx ingress controller
#    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
#    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
    - host: argo.rico-play.ids-dev.shoot.canary.k8s-hana.ondemand.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
#  tls:
#    - hosts:
#        - argo.ef87d110858c4a87a300.germanywestcentral.aksapp.io
#      secretName: argocd-secret
