spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/catenax-ng/devops-apps.git
    targetRevision: HEAD

certManager:
  installCRDs: true

ingressNginx:
  controller:
    ingressClassResource:
      default: true
    watchIngressWithoutClass: true
    config:
      # @url: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#enable-underscores-in-headers
      enable-underscores-in-headers: "true"
    extraArgs:
      default-ssl-certificate: "default/www-tls"  # K8_NAMESPACE/K8_SECRET_NAME @url: https://kubernetes.github.io/ingress-nginx/user-guide/tls/#default-ssl-certificate    
  defaultBackend:
    enabled: true
